[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = [
    "test",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
